# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'coolPer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for coolPer
  pod 'YYFast'
  pod 'HGCircularSlider'
  pod 'AAInfographics', :git => 'https://github.com/AAChartKit/AAChartKit-Swift.git', :branch => 'master'
  
end
