# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'langTao' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!
  
  # Pods for langTao
  pod 'YYFast'
  pod 'CRRefresh'
  pod 'JXPhotoBrowser'
  pod 'JXSegmentedView'
  pod 'YPImagePicker'
  
end
